services:
  - type: web
    name: ai-resume-ranker
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0