services:
  - type: web
    name: ai-resume-ranker
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
