services:
  - type: web
    name: ai-resume-ranker
    env: python
    buildCommand: |
      # Install requirements first
      pip install -r requirements.txt
      # Clean up any existing spaCy packages if they exist
      pip uninstall -y spacy thinc blis cython en-core-web-sm || true
      # Download NLTK data
      python -c "
      import nltk
      try:
          nltk.download('punkt', quiet=True)
          nltk.download('stopwords', quiet=True)
          nltk.download('averaged_perceptron_tagger', quiet=True)
          nltk.download('maxent_ne_chunker', quiet=True)
          nltk.download('words', quiet=True)
      except:
          print('NLTK download completed with some errors')
      "
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0