services:
  - type: web
    name: ai-resume-ranker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gcc g++ make
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      python -m spacy download en_core_web_sm || echo "spaCy download failed, using fallback"
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0